version: '3.9'

services:
  frontend:
    image: nginx
    ports:
      - "80:80"
    networks:
      - questdb-network
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

networks:
  questdb-network:
    driver: bridge
