version: '3.9'

services:
  quest-services:
    image: questdb/questdb:7.4.2
    ports:
      - "9001:9000"
      - "9009:9009"
      - "8812:8812"
      - "9003:9003"
    networks:
      - questdb-network
    volumes:
      - ./questdb/data:/var/lib/questdb

networks:
  questdb-network:
    driver: bridge
